import { GiftData, ThemeOption } from './types';
import dinoPantherLogo from './assets/images/dino_panther_same_size_1788091439765.jpg';

export const THEME_OPTIONS: ThemeOption[] = [
  {
    id: 'midnight-sky',
    name: 'Midnight Sky',
    description: 'Deep starry sky with glowing celestial light.',
    colors: ['#031c39', '#b2c8ed'],
  },
  {
    id: 'deep-cosmos',
    name: 'Deep Cosmos 3D',
    description: '3D swirling cosmic nebula with shooting stars.',
    colors: ['#0d0221', '#a259ff'],
  },
  {
    id: 'blush-romance',
    name: 'Blush Pink Night',
    description: 'Soft, sentimental twilight with warm glowing stars.',
    colors: ['#301216', '#fdc7cb'],
  },
  {
    id: 'sunset-squadron',
    name: 'Sunset Squadron',
    description: 'Golden hour horizon transitioning into starry night.',
    colors: ['#301216', '#e7c08a', '#fdc7cb'],
  },
  {
    id: 'starlight-lavender',
    name: 'Starlight Lavender',
    description: 'Dreamy purple galaxy with glittering constellations.',
    colors: ['#1e0036', '#c8b6ff'],
  },
  {
    id: 'eclipse-obsidian',
    name: 'Eclipse Obsidian & Gold',
    description: 'Luxurious dark velvet sky with radiant golden moon glow.',
    colors: ['#000d20', '#a68553'],
  },
  {
    id: 'pastel-aurora',
    name: 'Pastel Aurora',
    description: 'Dancing northern lights in soothing pastel tones.',
    colors: ['#0b2b26', '#80ed99'],
  },
  {
    id: 'sage-moonlight',
    name: 'Sage Garden Moonlight',
    description: 'Fresh botanical night with silver moonbeams.',
    colors: ['#1c291d', '#8a9a86'],
  },
];

export const FLOWER_OPTIONS = [
  {
    id: 'roses',
    name: 'Roses',
    tagline: 'CLASSIC ROMANCE',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBs6fEBo7E4Sase-Ba_vgc_ll5vEFJP9pXGaeVc9wZYog1ReE9Ed9X0YpZGQTuPjg8ZEgUUz9GdO_FNiyovN3XLYeaTNhYkgvNL6DoHDFPgg_C_a_wLaGdZD2PUqdv_xg4HyXIPavFqtzy4Qo0GnwGGu6LPTu1dHgBARmtWz_zJWnOQezfWQEffMVag2CkuWpaJQROpla3gyaV1WcF8iIzJj3r0iWsk9x0-bC6XZIfM9NQd7RY5NnfAGg',
  },
  {
    id: 'sunflowers',
    name: 'Sunflowers',
    tagline: 'SUNSHINE',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCQWRYq6KSpSUvCLPZyRTlaSm2yAcAEVo_voxzInTYsgiZXGtVxdDr-jZNqzNUyQm4RwygH0QVkg6RS6T7z-rUOE5yd8A_26rwsSwvL18_7JoZjcb4izfNwEmocEmrDZ_Hdder6an26a3mIbZ8rSo8h0KVLgmImkGaT_p6FotQjHKSUyhRQ6nUww0uJ0Hfk5wSEVgW51pQiJ1HXQ4tkr1zNg6xNltwXENJwsUNbG4T5lwOxrg7YXfD91g',
  },
  {
    id: 'daisies',
    name: 'Daisies',
    tagline: 'SIMPLE JOYS',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCeXxEdR8jz-VC3SuxK7YbYe-ODPnef_8yjUx8E9XIYvLhjE_RcU1abdcCXXAOj1qhSK-9LwZoeWy1V8YRpO6oFwi4LbFdYmP4Bd5vI4q7a0m4BForwtD84P26N0S39L6SPbtCqnS8msiy6YOoLFf-E3nNG8ljgE1EMVtwJQrOqggRtZe6rC36e8Swd7CA3hXGsgy7vYPowdO1CclAo7Jeb7U8xeITQGaNoNjAzpTGnDcdbY8LfU25crA',
  },
  {
    id: 'tulips',
    name: 'Tulips',
    tagline: 'ELEGANCE',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDtNiCCfT_rssUWSqW1VaTAX8JeHqWC3eV-dyMjRZ6S06qqcol3-6E_bb62raYK46hDooyVXJ0d5MrN4aHnzZyQO4mf-XeEfHkH_gs2JJdpv3CXy8b6ULNOG82URkMvAxD8M7g2L_u6WKlb9y5uay1b9VaqfassruQ_oI0umN8Ipss16GI4Lv1uIBW2RjmCTT9IakN_ch_VgMwFJifYhwU6A9SjRZmeP-B0I8aJmF-gy6sWIYpcakR0OQ',
  },
  {
    id: 'lavender',
    name: 'Lavender',
    tagline: 'CALMING',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAh905zmZxPRuC_B90_hPKxhfcMbmEXh5KKiRS0P1_00ZlGqY9w_0AwSyDZwmDkSaV7-5dTlhgsRYjLqykpGw8OJVL0l6br1UZhLpTRaSw7y-oBgzVCwlhxo8JPZOixMzYclMvx5LgAH4TsIrX83DnYV-RrWahCaOVZaGkUgZ1gKlhBm485aSRvwHP8agVBEE_bfbXcwl_tEuCpjtQLSP-vbY2r9Oxo98bQDD37YP1WNG4KrDluFY4UVQ',
  },
  {
    id: 'peonies',
    name: 'Peonies',
    tagline: 'DREAMY',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAr-iWV2A5j-c6tXTe437VzwkDecRyjiVMV8qHTAVXpUZDg_RL5HuSRGP62lPp4H0xZTYYjCBXjrxjuZrq_4fru0Vf-mhktt7yBRV9lW_mhScUeW5z24pNu71fGVguoamqmhhgQOyBFWHh2MAMY825kvye2ow_9EQLmGxty3v4oBVj6fICkN0s6dYlJ_ZgXLiLHN7ri2lOU2EDjQ2y7C2D4LJ3CLfKmxcYIs3s5i4YqZThg77jWPNuVCg',
  },
  {
    id: 'hydrangeas',
    name: 'Hydrangeas',
    tagline: 'FULL HEART',
    imageUrl: 'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400',
  },
  {
    id: 'lilies',
    name: 'Lilies',
    tagline: 'PURITY',
    imageUrl: 'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=400',
  },
  {
    id: 'orchids',
    name: 'Orchids',
    tagline: 'EXOTIC BEAUTY',
    imageUrl: 'https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?w=400',
  },
  {
    id: 'cherry-blossoms',
    name: 'Cherry Blossoms',
    tagline: 'SWEET SPRING',
    imageUrl: 'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=400',
  },
];

export const WRAP_STYLES = [
  'Classic Wrap',
  'Wildflower Loose Bunch',
  'Navy Ribbon Bundle',
  'Minimal Single Stem',
];

export const NATURE_ELEMENTS = [
  { id: 'flowers', name: 'Flowers', icon: 'local_florist', color: 'text-primary' },
  { id: 'twinkling-stars', name: 'Twinkling Stars', icon: 'stars', color: 'text-[#a68553]' },
  { id: 'shooting-stars', name: 'Shooting Stars', icon: 'auto_awesome', color: 'text-[#b2c8ed]' },
  { id: 'paws', name: 'Paws', icon: 'pets', color: 'text-[#7c5357]' },
  { id: 'rain', name: 'Rain', icon: 'rainy', color: 'text-[#4b5f7f]' },
  { id: 'leaves', name: 'Leaves', icon: 'energy_savings_leaf', color: 'text-[#e7c08a]' },
  { id: 'wind', name: 'Wind', icon: 'air', color: 'text-[#c4c6ce]' },
  { id: 'rainbow', name: 'Rainbow', icon: 'qr_code_2', color: 'text-[#eeb9bd]' },
  { id: 'clouds', name: 'Clouds', icon: 'cloud', color: 'text-[#b2c8ed]' },
  { id: 'sunset', name: 'Sunset', icon: 'wb_twilight', color: 'text-[#a68553]' },
  { id: 'water', name: 'Water', icon: 'water_drop', color: 'text-[#4b5f7f]' },
];

export const CHARM_OPTIONS = [
  { id: 'kiss', name: 'Kiss', icon: 'favorite', color: 'text-[#7c5357]' },
  { id: 'hug', name: 'Hug', icon: 'hail', color: 'text-[#a68553]' },
  { id: 'flowers', name: 'Flowers', icon: 'local_florist', color: 'text-[#7c5357]' },
  { id: 'icecream', name: 'Ice Cream', icon: 'icecream', color: 'text-[#b2c8ed]' },
  { id: 'coffee', name: 'Coffee', icon: 'local_cafe', color: 'text-[#321f00]' },
  { id: 'star', name: 'Star', icon: 'star', color: 'text-[#e7c08a]' },
  { id: 'cuddle-paw', name: 'Cuddle Paw', icon: 'pets', color: 'text-[#1e1b16]' },
  { id: 'safe-flight', name: 'Safe Flight', icon: 'flight_takeoff', color: 'text-[#000d20]' },
  { id: 'love-note', name: 'Love Note', icon: 'mail', color: 'text-[#7c5357]' },
];

export const INITIAL_COLLECTION: GiftData[] = [
  {
    id: 'gift-1',
    title: "A Little Garden for My Panther 🐾✈️",
    theme: 'Midnight Sky',
    coverImage: dinoPantherLogo,
    flowers: ['Roses', 'Peonies', 'Lavender'],
    wrapStyle: 'Navy Ribbon Bundle',
    natureElements: ['Twinkling Stars', 'Shooting Stars', 'Paws'],
    charms: ['Kiss', 'Coffee', 'Safe Flight', 'Star'],
    photoUrl: dinoPantherLogo,
    photoCaption: 'Looking at the exact same moon from Sialkot to Ormara.',
    videoUrl: '',
    songUrl: 'https://open.spotify.com/track/2yN2I1J3u5p9',
    songTitle: 'Moon River',
    songArtist: 'Frank Ocean',
    moodTag: 'Romantic',
    captainsLog: 'Sending love across the skies from Sialkot to Balochistan...',
    locketPhoto: dinoPantherLogo,
    locketCaption: 'The prettiest smile under the stars 🥹',
    distanceMiles: 770,
    fromCity: 'Sialkot, Punjab (Pakistan)',
    toCity: 'Ormara, Balochistan (Pakistan)',
    fromCoords: { lat: 32.4945, lon: 74.5229 },
    toCoords: { lat: 25.2088, lon: 64.6357 },
    fromPerson: 'Dino 🦖',
    toPerson: 'Panther 🐾✈️',
    letter: "From Sialkot with all my heart to my man in Ormara, Balochistan. No matter how many miles lie between us, every heartbeat and every prayer belongs to you. Can't wait until we're together again 💚",
    date: 'August 14, 2026',
    published: true,
    shareCode: '3x9a7k',
    enabledSlides: [0, 1, 2, 3, 4, 5, 6, 7],
    chatMessages: [
      {
        id: 'msg-1',
        sender: 'dino',
        text: 'Hey Moon! 🌙 The stars look extra bright over Sialkot tonight. Please watch over my favorite Panther in Ormara...',
        time: '9:45 PM',
        heartCount: 3,
      },
      {
        id: 'msg-2',
        sender: 'moon',
        text: 'Rawr! 🦕 I can see both of you from up here! Shining light over the Balochistan coast and Punjab tonight ✨',
        time: '9:46 PM',
        heartCount: 5,
      },
      {
        id: 'msg-3',
        sender: 'dino',
        text: 'Thank you Moon! Count down the days until we stare at the sky together again! 💚',
        time: '9:47 PM',
        heartCount: 4,
      },
    ],
  },
  {
    id: 'gift-2',
    title: 'Morning Brew & Longing',
    theme: 'Coffee & Cream',
    flowers: ['Sunflowers', 'Daisies'],
    wrapStyle: 'Wildflower Loose Bunch',
    natureElements: ['Sunset', 'Clouds'],
    charms: ['Coffee', 'Hug', 'Love Note'],
    photoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBPGcSxhpe9rQuqZALqADA_vf52z7N3wf0glvYLPSuZoGKiBXcIW58PW0_aI8pJG-G2kgM3QCHIyDE23u0VGbmjCccOhMGPXunARI0pxcu_STCaOisgSxgMOwCCmrwSY6SpEmph3iJGBoSKrAIxj2meixQleVAR6n5rkvzLgOizk-VvRbR_Cr4Th1-Yb_TRut2v-VZBDJJlmwd2tkFrWr9c3UoCZYnEkoKAMQpvOlj2-AaX3kVbWoEbmw',
    photoCaption: 'Morning chai & coffee, wish you were here.',
    videoUrl: '',
    songUrl: '',
    songTitle: 'Warm Coffee',
    songArtist: 'Lo-Fi Chill',
    moodTag: 'Cozy & Soft',
    captainsLog: 'Steaming cups, thinking of you.',
    locketPhoto: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDFsW6l3mqs20fWjIdT3zkNoAolwOP80rwGsgEqASKkL13saG7FDTygP6VCNnaPriHP4nhsrc2_rSBfBCx6_H_DjAIMtDoNRXdvKSirstLnOsoH8ljYnTNu_PSrPUPXlUymArOjfHWAeWjfdVbMfjFXYG3tPwt0CyNRyZo1SDHnsoQj6kZXu-6iyXepKI8-vzpbNL7BD-LuRsQQycZv4WJRqkkvHfzR4I8HeTFdMMM3C6Tm0l1S3xGGCg',
    locketCaption: 'Always smiling.',
    distanceMiles: 770,
    fromCity: 'Sialkot, Punjab',
    toCity: 'Ormara, Balochistan',
    fromCoords: { lat: 32.4945, lon: 74.5229 },
    toCoords: { lat: 25.2088, lon: 64.6357 },
    fromPerson: 'Dino 🦖',
    toPerson: 'Panther 🐾✈️',
    letter: 'Sending warm vibes across the miles from Sialkot to Ormara. Counting down the moments until our next flight together.',
    date: 'August 10, 2026',
    published: true,
    shareCode: '7k2m9p',
    enabledSlides: [0, 1, 2, 3, 4, 5, 6, 7],
    chatMessages: [
      {
        id: 'msg-coffee-1',
        sender: 'dino',
        text: 'Morning Moon! Just brewed coffee in Sialkot and wishing Panther was sitting right across the table. ☕',
        time: '8:15 AM',
      },
      {
        id: 'msg-coffee-2',
        sender: 'moon',
        text: 'The morning glow reaches all the way to Ormara coast right now! Have a beautiful day! 🌤️✨',
        time: '8:16 AM',
      },
    ],
  },
];
